name: iphonedation
favicon: null
layout_spectrum: 0.8505352078936994
typography_spectrum: 0.07244364451617002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00ffff'
    - '#007575'
    - '#002222'
    - '#00a1a1'
  brandStrength: 0.5
  lightness: 0.08704534056596458
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
